# Required to run your project under the correct environment.
language: php

# Versions of PHP you want your project run with.
php:
  - 5.5
  - 5.6
  - hhvm

# Commands to be run before your environment runs.
before_script:
  #- cp .env.travis .env
  - mysql -e "create database doctor_client_portal;"
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - php artisan key:generate

script:
  - vendor/bin/phpunit